(function(){
'use strict';
const KEY='chesstochess.player.v1';
const MAX_GAMES=50,MAX_TRAINING=100,MAX_ACTIVITY=100;
const now=()=>new Date().toISOString();
function fresh(){const t=now();return{schemaVersion:1,createdAt:t,updatedAt:t,preferences:{botDifficulty:'medium',boardFlipped:false},totals:{games:0,wins:0,losses:0,draws:0,puzzlesAttempted:0,puzzlesSolved:0,hintsUsed:0},motifStats:{},games:[],trainingSessions:[],recentActivity:[]}}
function safeInt(v){v=Number(v);return Number.isFinite(v)&&v>=0?Math.floor(v):0}
function normalize(raw){const base=fresh();if(!raw||raw.schemaVersion!==1)return base;return{...base,...raw,preferences:{...base.preferences,...raw.preferences},totals:{...base.totals,...raw.totals},motifStats:raw.motifStats&&typeof raw.motifStats==='object'?raw.motifStats:{},games:Array.isArray(raw.games)?raw.games.slice(-MAX_GAMES):[],trainingSessions:Array.isArray(raw.trainingSessions)?raw.trainingSessions.slice(-MAX_TRAINING):[],recentActivity:Array.isArray(raw.recentActivity)?raw.recentActivity.slice(-MAX_ACTIVITY):[]}}
function read(){try{return normalize(JSON.parse(localStorage.getItem(KEY)))}catch(_){return fresh()}}
let state=read();
function save(){state.updatedAt=now();state.games=state.games.slice(-MAX_GAMES);state.trainingSessions=state.trainingSessions.slice(-MAX_TRAINING);state.recentActivity=state.recentActivity.slice(-MAX_ACTIVITY);localStorage.setItem(KEY,JSON.stringify(state));renderDashboard();return state}
function migrateLegacy(){if(localStorage.getItem(KEY))return;const solved=safeInt(localStorage.getItem('ct-solved'));const attempts=safeInt(localStorage.getItem('ct-session-attempts'));const hints=safeInt(localStorage.getItem('ct-session-hints'));if(solved||attempts||hints){state.totals.puzzlesSolved=solved;state.totals.puzzlesAttempted=solved+attempts;state.totals.hintsUsed=hints;state.recentActivity.push({id:'legacy-'+Date.now(),type:'migration',at:now(),label:'Imported existing training progress'});save()}else save()}
function addActivity(type,label,meta={}){state.recentActivity.push({id:type+'-'+Date.now(),type,at:now(),label,...meta})}
function recordGame(game){if(!game||!game.result)return;const item={id:game.id||'game-'+Date.now(),startedAt:game.startedAt||null,completedAt:game.completedAt||now(),result:game.result,difficulty:game.difficulty||state.preferences.botDifficulty,moves:Array.isArray(game.moves)?game.moves:[],finalFen:game.finalFen||null,termination:game.termination||null,analysisStatus:game.analysisStatus||'not_analyzed'};state.games.push(item);state.totals.games++;if(item.result==='win')state.totals.wins++;else if(item.result==='loss')state.totals.losses++;else state.totals.draws++;addActivity('game',(item.result==='win'?'Won':item.result==='loss'?'Lost':'Drew')+' vs computer',{recordId:item.id});save()}
function recordTraining(session){if(!session)return;const item={id:session.id||'training-'+Date.now(),puzzleId:session.puzzleId||null,motifs:Array.isArray(session.motifs)?session.motifs:[],startedAt:session.startedAt||null,completedAt:session.completedAt||now(),solved:!!session.solved,wrongAttempts:safeInt(session.wrongAttempts),hints:safeInt(session.hints),accuracy:Math.max(0,Math.min(100,Number(session.accuracy)||0))};state.trainingSessions.push(item);state.totals.puzzlesAttempted++;if(item.solved)state.totals.puzzlesSolved++;state.totals.hintsUsed+=item.hints;item.motifs.forEach(m=>{const key=String(m).toLowerCase();const x=state.motifStats[key]||{attempts:0,solved:0};x.attempts++;if(item.solved)x.solved++;state.motifStats[key]=x});addActivity('training',(item.solved?'Solved ':'Practiced ')+(item.puzzleId||'puzzle'),{recordId:item.id});save()}
function setPreference(name,value){if(!(name in state.preferences))return;state.preferences[name]=value;save()}
function accuracy(){const rows=state.trainingSessions;if(rows.length){const total=rows.reduce((n,x)=>n+(Number(x.accuracy)||0),0);return Math.round(total/rows.length)}const attempted=state.totals.puzzlesAttempted;return attempted?Math.round(state.totals.puzzlesSolved/attempted*100):0}
function renderDashboard(){const root=document.getElementById('playerDashboard');if(!root)return;const t=state.totals;const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set('dashRecord',t.wins+' / '+t.losses+' / '+t.draws);set('dashGames',t.games);set('dashSolved',t.puzzlesSolved);set('dashAccuracy',accuracy()+'%');const activity=document.getElementById('recentActivity');if(activity){const rows=state.recentActivity.slice(-4).reverse();activity.innerHTML=rows.length?rows.map(x=>'<div class="activity-row"><span>'+escapeHtml(x.label)+'</span><small>'+relativeTime(x.at)+'</small></div>').join(''):'<div class="activity-empty">Play a game or solve a puzzle to start your history.</div>'}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function relativeTime(iso){const d=Date.now()-Date.parse(iso);if(!Number.isFinite(d))return '';const m=Math.floor(d/60000);if(m<1)return'just now';if(m<60)return m+'m ago';const h=Math.floor(m/60);if(h<24)return h+'h ago';return Math.floor(h/24)+'d ago'}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='chesstochess-player-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
function reset(){if(!confirm('Reset all Chesstochess player progress? This cannot be undone unless you export it first.'))return;localStorage.removeItem(KEY);localStorage.removeItem('chesstochess.weaknesses.v1');localStorage.removeItem('chesstochess.analysis.report.v1');['ct-puzzle-index','ct-correct','ct-solved','ct-session-attempts','ct-session-hints','ct-session-correct'].forEach(k=>localStorage.removeItem(k));state=fresh();save();location.reload()}
window.ChesstochessPlayer={get:()=>structuredClone(state),save,recordGame,recordTraining,setPreference,exportData,reset,renderDashboard};
migrateLegacy();
document.addEventListener('DOMContentLoaded',()=>{renderDashboard();document.getElementById('exportDataBtn')?.addEventListener('click',exportData);document.getElementById('resetDataBtn')?.addEventListener('click',reset)});
})();